In [1]:
import numpy as np
import random
import pandas as pd

In [2]:
def createRandomMatrix():
    matrix = []
    for i in range(3):
        row = []
        for j in range(3):
            row.append(random.randint(-10, 10))
        matrix.append(row)    
    return matrix    

In [23]:
matrix1 = createRandomMatrix()
matrix2 = createRandomMatrix()
matrix3 = createRandomMatrix()

print(matrix1)
print(matrix2)
print(matrix3)

[[6, -10, -5], [-2, -4, 8], [-5, 9, -5]]
[[6, 2, 0], [-3, 9, -6], [8, 0, 4]]
[[1, 7, 2], [9, -6, 8], [-3, -10, -6]]


In [4]:
inverse_matrix1 = np.linalg.inv(matrix1)
inverse_matrix2 = np.linalg.inv(matrix2)
inverse_matrix3 = np.linalg.inv(matrix3)
print(inverse_matrix1)
print(inverse_matrix2)
print(inverse_matrix3)

[[ 0.27586207  0.03448276 -0.03448276]
 [ 0.70114943  0.37931034 -0.04597701]
 [ 0.59770115  0.24137931  0.09195402]]
[[ 0.06077348 -0.02762431  0.04972376]
 [ 0.06629834  0.06077348  0.02394107]
 [ 0.00552486  0.08839779  0.14088398]]
[[-0.13744076  0.13981043  0.12085308]
 [ 0.09952607 -0.11848341  0.03317536]
 [ 0.16587678 -0.03080569 -0.11137441]]


In [5]:
result1 = np.dot(matrix1, inverse_matrix1)
result2 = np.dot(matrix2, inverse_matrix2)
result3 = np.dot(matrix3, inverse_matrix3)
#np.set_printoptions(precision=3, suppress=True)
print(result1)
print(result2)
print(result3)

[[ 1.00000000e+00  2.77555756e-17  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00 -2.77555756e-17]
 [-2.22044605e-16 -1.94289029e-16  1.00000000e+00]]
[[ 1.00000000e+00  5.55111512e-17 -1.11022302e-16]
 [ 1.21430643e-17  1.00000000e+00  0.00000000e+00]
 [-7.45931095e-17  8.32667268e-17  1.00000000e+00]]
[[1.00000000e+00 2.77555756e-16 1.11022302e-16]
 [5.55111512e-17 1.00000000e+00 1.38777878e-17]
 [1.66533454e-16 1.73472348e-16 1.00000000e+00]]


In [18]:
df = pd.read_csv('C:\\Users\\tanma\\Downloads\\kc_house_data.csv')
features_to_ignore = ['id', 'date', 'zipcode']

df_subset = df.drop(columns = features_to_ignore)

max_values_per_feature_sub = df_subset.max(axis=0)
min_values_per_feature_sub = df_subset.min(axis=0)

def calculate_average(column):
    total = sum(column)
    count = len(column)
    return round(total / count, 4) if count > 0 else 0

def calculate_variance(column):
    mean = calculate_average(column)
    count = len(column)
    sum_squared_diff = sum((x - mean)** 2 for x in column)
    variance = round(sum_squared_diff / (len(column) - 1), 4)
    return variance

def calculate_correlation(column_x, column_y):
    mean_x = calculate_average(column_x)
    mean_y = calculate_average(column_y)
    numerator = sum(((column_x[i] - mean_x) * (column_y[i] - mean_y))
                    for i in range(len(column_y)))
    denominator = (sum((column_x[i] - mean_x) ** 2
                       for i in range(len(column_x))) *
                   sum((column_y[i] - mean_y) ** 2
                       for i in range(len(column_y)))) ** 0.5
    return round(numerator / denominator, 4)

pd.set_option('display.float_format', '{:.4f}'.format)

print("Max values:\n")
print(max_values_per_feature_sub)
print("\n")

print("Min values:\n")
print(min_values_per_feature_sub)
print("\n")

Max values:

price           7700000.0000
bedrooms             33.0000
bathrooms             8.0000
sqft_living       13540.0000
sqft_lot        1651359.0000
floors                3.5000
waterfront            1.0000
view                  4.0000
condition             5.0000
grade                13.0000
sqft_above         9410.0000
sqft_basement      4820.0000
yr_built           2015.0000
yr_renovated       2015.0000
lat                  47.7776
long               -121.3150
sqft_living15      6210.0000
sqft_lot15       871200.0000
dtype: float64


Min values:

price           75000.0000
bedrooms            0.0000
bathrooms           0.0000
sqft_living       290.0000
sqft_lot          520.0000
floors              1.0000
waterfront          0.0000
view                0.0000
condition           1.0000
grade               1.0000
sqft_above        290.0000
sqft_basement       0.0000
yr_built         1900.0000
yr_renovated        0.0000
lat                47.1559
long             -122.5190
sqf

In [15]:
print("Averages:\n")
averages = []
for column in df_subset.columns:
    average = calculate_average(df_subset[column])
    print(f"{column}: \t\t{average}")
    averages.append(average)
averages = np.array(averages)    
max_avg = averages.max(axis = 0)
min_avg = averages.min(axis = 0)
max_avg_idx = np.argmax(averages, axis = 0)
min_avg_idx = np.argmin(averages, axis = 0)
print("\n")
print(f"Max average is {df_subset.columns[max_avg_idx]} : {max_avg}")
print(f"Min average is {df_subset.columns[min_avg_idx]} : {min_avg}")
print("\n") 

Averages:

price: 		540088.1418
bedrooms: 		3.3708
bathrooms: 		2.1148
sqft_living: 		2079.8997
sqft_lot: 		15106.9676
floors: 		1.4943
waterfront: 		0.0075
view: 		0.2343
condition: 		3.4094
grade: 		7.6569
sqft_above: 		1788.3907
sqft_basement: 		291.509
yr_built: 		1971.0051
yr_renovated: 		84.4023
lat: 		47.5601
long: 		-122.2139
sqft_living15: 		1986.5525
sqft_lot15: 		12768.4557


Max average is price : 540088.1418
Min average is long : -122.2139




In [13]:
variances = []
print("Variance values:\n")
for column in df_subset.columns:
    variance = calculate_variance(df_subset[column])
    print(f"{column}: \t\t{variance}")
    variances.append(variance)
variances = np.array(variances)    
max_var = variances.max(axis = 0)
min_var = variances.min(axis = 0)
max_var_idx = np.argmax(variances, axis = 0)
min_var_idx = np.argmin(variances, axis = 0)
print("\n")
print(f"Max variance is {df_subset.columns[max_var_idx]} : {max_var}")
print(f"Min variance is {df_subset.columns[min_var_idx]} : {min_var}")
print("\n")



Variance values:

price: 		134782378397.2614
bedrooms: 		0.865
bathrooms: 		0.5932
sqft_living: 		843533.6814
sqft_lot: 		1715658774.1755
floors: 		0.2916
waterfront: 		0.0075
view: 		0.5872
condition: 		0.4235
grade: 		1.3817
sqft_above: 		685734.6673
sqft_basement: 		195872.6684
yr_built: 		862.7973
yr_renovated: 		161346.2119
lat: 		0.0192
long: 		0.0198
sqft_living15: 		469761.2399
sqft_lot15: 		745518225.3404


Max variance is price : 134782378397.2614
Min variance is waterfront : 0.0075




In [21]:
print("Correlation:\n")
correlations = []
for column in df_subset.columns:
    if column == 'price':
        pass
    else:
        correlation = calculate_correlation(df['price'], df[column])
        print(f"{column}: \t\t{correlation}")
        correlations.append(correlation)
print("\n")    
correlations = np.array(correlations)    
max_corr = correlations.max(axis = 0)
max_corr_idx = np.argmax(correlations, axis = 0)
print(f"The feature with the maximum correlation")
print(f"{df_subset.columns[max_corr_idx + 1]} with value {max_corr}")
print("All features are positively correlated with the price")
print("No features are negatively correlated with the price")
pd.reset_option('display.float_format')

Correlation:

bedrooms: 		0.3083
bathrooms: 		0.5251
sqft_living: 		0.702
sqft_lot: 		0.0897
floors: 		0.2568
waterfront: 		0.2664
view: 		0.3973
condition: 		0.0364
grade: 		0.6674
sqft_above: 		0.6056
sqft_basement: 		0.3238
yr_built: 		0.054
yr_renovated: 		0.1264
lat: 		0.307
long: 		0.0216
sqft_living15: 		0.5854
sqft_lot15: 		0.0824


The feature with the maximum correlation
sqft_living with value 0.702
All features are positively correlated with the price
No features are negatively correlated with the price
